version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore\\(deps\\):"
  groups:
    - title: "Breaking Changes"
      regexp: '^.*?!:.+$'
      order: 0
    - title: "Features"
      regexp: '^feat.*'
      order: 1
    - title: "Bug Fixes"
      regexp: '^fix.*'
      order: 2
    - title: "Other"
      order: 999

release:
  github:
    owner: sirerun
    name: mcp-registry
  prerelease: auto
  make_latest: true
